### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by Turch99** [uqqu/frequency_analysis#1]
Hello.
I am not a very advanced user, so I immediately apologize if the question is obvious.
I have a problem installing a module.

`pip install frequency-analysis` 

returns me:
```
Preparing metadata (setup.py) ... error
error: subprocess-exited-with-error
```

```
note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```

I have python 3.11
cmd Windows

What are the solution methods?

**Comment by Turch99** [comment]
```
python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\xxx\xxx\xxx\frequency-analysis_b3eb87be980d46ab89cd6b17991f4b4f\setup.py", line 5, in <module>
          long_description = (this_directory / "README.rst").read_text()
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\xxx\xxx\xxx\Local\Programs\Python\Python311\Lib\pathlib.py", line 1059, in read_text
          return f.read()
                 ^^^^^^^^
        File "C:\xxx\xxx\xxx\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 1423: character maps to <undefined>
      [end of output]
```

I understand that the error is related to the encoding, but I don't quite know how I can fix it.

**Comment by uqqu** [comment]
It looks like I forgot to set the correct encoding. Thanks for the notification. Probably corrected it. Try now (v0.1.4.4)

**Comment by Turch99** [comment]
Yes thank you! The installation was successful.

**Comment by uqqu** [comment]
Great!
